sudo: required
services: 
  - docker
before_install:
  - docker build -t docker-react-image -f ./client/Dockerfile.dev ./client
script: 
  - docker run -e CI=true docker-react-image npm run test
language: generic
after_success:
  - docker build -t naman201995/multi-client ./client
  - docker build -t naman201995/multi-nginx ./nginx
  - docker build -t naman201995/multi-server ./server
  - docker build -t naman201995/multi-worker ./worker
  # Login to Docker CLI
  - echo $Docker_Pass | docker login -u $Docker_ID --password-stdin
  #Push the images to Docker Hub
  - docker push naman201995/multi-client
  - docker push naman201995/multi-nginx
  - docker push naman201995/multi-server
  - docker push naman201995/multi-worker
deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-954640347509"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

